name: "nix"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: cachix/install-nix-action@v30
      - run: nix develop -L .# -c dune build @runtest @check
